name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Download model
        run: |
          curl -O ${{secrets.MODEL_SEGMENTATION_URL}}
          mv model_segmentation.h5 ./app/model/model_segmentation.h5
    
      - name: Set Up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with: 
          project_id: bangkit-breeze
          service_account_key: ${{secrets.GCLOUD_AUTH}}

      - name: Configure Docker to use gcloud 
        run: |
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet

      - name: Set Environment Variables
        run: |
          echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
            
      - name: Build and Push Docker Image 
        run: |
          export IMAGE_TAG=$(git rev-parse --short ${{github.sha}})
          export IMAGE_NAME=asia-southeast2-docker.pkg.dev/bangkit-breeze/backend/machine-learning:${IMAGE_TAG}
          docker build  --build-arg PORT=$PORT \
              -t ${IMAGE_NAME} .
          docker push ${IMAGE_NAME}

      - name: Deploy to Cloud Run
        run: |
          export IMAGE_TAG=$(git rev-parse --short ${{github.sha}})
          export IMAGE_NAME=asia-southeast2-docker.pkg.dev/bangkit-breeze/backend/machine-learning:${IMAGE_TAG}
          gcloud run deploy machine-learning-api --image ${IMAGE_NAME} --region asia-southeast2 --allow-unauthenticated